random-filter-s:
    wm_filter:
      docker-tag: neurips23-filter-wm_filter
      module: neurips23.filter.wm_filter.wm_filter
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [{"nprobe": 1},
              {"nprobe":2},
              {"nprobe":4}]    
random-s:
    wm_filter:
      docker-tag: neurips23-filter-wm_filter
      module: neurips23.filter.wm_filter.wm_filter
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [{"nprobe": 1},
              {"nprobe":2},
              {"nprobe":4}]
yfcc-10M-unfiltered:
    wm_filter:
      docker-tag: neurips23-filter-wm_filter
      module: neurips23.filter.wm_filter.wm_filter
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,PQ96x4fs,Refine(SQ8)", "threads": 8, "train_size": 2000000}]
          query-args: |
            [{"nprobe": 1, "k_factor":20}, {"nprobe": 4, "k_factor":20}, {"nprobe": 16, "k_factor":20}, {"nprobe": 64, "k_factor":20}]
yfcc-10M:
    wm_filter:
      docker-tag: neurips23-filter-wm_filter
      module: neurips23.filter.wm_filter.wm_filter
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "threads": 8,
              "train_size": 2000000,
              "type": "direct"
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003},
             {"nprobe": 4, "mt_threshold":0.0003},
             {"nprobe": 16, "mt_threshold":0.0003},
             {"nprobe": 32, "mt_threshold":0.0003},
             {"nprobe": 64, "mt_threshold":0.0003},
             {"nprobe": 96, "mt_threshold":0.0003},
             {"nprobe": 1, "mt_threshold":0.0001},
             {"nprobe": 4, "mt_threshold":0.0001},
             {"nprobe": 16, "mt_threshold":0.0001},
             {"nprobe": 32, "mt_threshold":0.0001},
             {"nprobe": 64, "mt_threshold":0.0001},
             {"nprobe": 96, "mt_threshold":0.0001},
             {"nprobe": 1, "mt_threshold":0.001}, 
             {"nprobe": 4, "mt_threshold":0.001}, 
             {"nprobe": 16, "mt_threshold":0.001}, 
             {"nprobe": 32, "mt_threshold":0.001}, 
             {"nprobe": 64, "mt_threshold":0.001}, 
             {"nprobe": 96, "mt_threshold":0.001}
            ]
yfcc-10M-2:
    wm_filter:
      docker-tag: neurips23-filter-wm_filter
      module: neurips23.filter.wm_filter.wm_filter
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "threads": 8,
              "train_size": 2000000,
              "type": "direct"
            }]
          query-args: |
            [
             {"nprobe": 128, "mt_threshold":0.00001, "max_codes": 2000}
            ]
